version: '3.8'

services:
  redis:
    restart: always
    image: bitnami/redis:latest
    container_name: pixiviz-redis
    hostname: pixiviz-redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./redis:/bitnami/redis/data
    healthcheck:
      test: "redis-cli -a ${REDIS_PASSWORD} ping"
      interval: 5s
      retries: 20

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: pixiviz-tunnel
    hostname: pixiviz-tunnel
    restart: unless-stopped
    command: tunnel run ${TUNNEL_TOKEN}
    depends_on:
      - api-service
    links:
      - api-service

  api-service:
    build: .
    container_name: pixiviz-api-service
    hostname: pixiviz-api-service
    volumes:
      - ./config:/usr/local/pixiviz-api/config
      - ./refreshToken:/usr/local/pixiviz-api/refreshToken
      - ./logs:/usr/local/pixiviz-api/logs
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - PIXIV_TOKEN=${PIXIV_TOKEN}
      - SAFE_KEY=${SAFE_KEY}
    networks:
      - pixiviz-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - redis
    links:
      - redis