version: '3.8'

services:
  redis:
    restart: always
    image: bitnami/redis:latest
    container_name: pixiviz-redis
    environment:
      - REDIS_PASSWORD=password
    networks:
      - pixiviz-internal
    volumes:
      - ./redis:/bitnami/redis/data
    healthcheck:
      test: "redis-cli -a password ping"
      interval: 5s
      retries: 20

  service:
    build: .
    ports:
      - "3000:3000"
    container_name: pixiviz-api-service
    volumes:
      - ./config:/usr/src/app/config
      - ./refreshToken:/usr/src/app/refreshToken
      - ./logs:/usr/src/app/logs
    networks:
      - pixiviz-internal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  pixiviz-internal:
    internal: true