version: '3.8'

services:
  redis:
    restart: always
    image: bitnami/redis:latest
    container_name: pixiviz-redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - pixiviz-service
      - pixiviz-tunnel
    volumes:
      - ./redis:/bitnami/redis/data
    healthcheck:
      test: "redis-cli -a ${REDIS_PASSWORD} ping"
      interval: 5s
      retries: 20

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: pixiviz-tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - pixiviz-service
      - pixiviz-tunnel
    depends_on:
      - service

  service:
    build: .
    ports:
      - "3000:3000"
    container_name: pixiviz-api-service
    volumes:
      - ./config:/usr/local/pixiviz-api/config
      - ./refreshToken:/usr/local/pixiviz-api/refreshToken
      - ./logs:/usr/local/pixiviz-api/logs
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - PIXIV_TOKEN=${PIXIV_TOKEN}
      - SAFE_KEY=${SAFE_KEY}
    networks:
      - pixiviz-service
      - pixiviz-tunnel
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  pixiviz-service:
    internal: true
  pixiviz-tunnel:
    internal: false
